sys-libs/ncurses: version bump: 5.9-r2

diff --git a/portage_diffs/latest/sys-libs_ncurses b/portage_diffs/latest/sys-libs_ncurses
--- a/portage_diffs/latest/sys-libs_ncurses
+++ b/portage_diffs/latest/sys-libs_ncurses
@@ -133,7 +133,7 @@
  	# For some reason, sources depends on pc-files which depends on
  	# compiled libraries which depends on sources which ...
  	# Manually delete the pc-files file so the install step will
-@@ -197,17 +258,39 @@
+@@ -197,17 +258,38 @@
  
  	if need-libtool; then
  		# Move dynamic ncurses libraries into /lib
@@ -142,11 +142,10 @@
 -		for f in "${ED}"usr/$(get_libdir)/lib{,n}curses{,w}$(get_libname)*; do
 +		local libpfx=lib
 +		local shlibdir=$(get_libdir)
-+		local postfix=
-+		[[ ${CHOST} == *-cygwin* ]] && { libpfx=cyg; shlibdir=bin; postfix=-10; }
++		local suffix=
++		[[ ${CHOST} == *-cygwin* ]] && { libpfx=cyg; shlibdir=bin; suffix=-10; dodir /$(get_libdir); }
 +		dodir /${shlibdir}
-+		[[ ${CHOST} == *-cygwin* ]] && dodir /$(get_libdir)
-+		for f in "${ED}"usr/${shlibdir}/${libpfx}{,n}curses{,w}${postfix}$(get_libname)*; do
++		for f in "${ED}"usr/${shlibdir}/${libpfx}{,n}curses{,w}${suffix}$(get_libname)*; do
  			[[ -f ${f} ]] || continue
 -			mv "${f}" "${ED}"$(get_libdir)/ || die "could not move ${f#${ED}}"
 +			einfo "moving \"/${f#${ED}}\" to \"/${shlibdir}/\"."
@@ -154,9 +153,9 @@
 +			[[ ${CHOST} == *-cygwin* ]] && {
 +				local x="$( dirname ${f} )"
 +				x="${x%${shlibdir}}$(get_libdir)"
-+				x="${x}/lib$( foo=$(basename ${f}); foo="${foo%-10.dll}" ; echo ${foo#cyg} ).dll.a"
-+				einfo "moving \"/${x#${ED}}\" to \"/lib/\"."
-+				mv "${x}" "${ED}"lib/ || die "could not move /${x#${ED}}"
++				x="${x}/lib$( foo=$(basename ${f}); foo="${foo%${suffix}.dll}" ; echo ${foo#cyg} ).dll.a"
++				einfo "moving \"/${x#${ED}}\" to \"/$(get_libdir)/\"."
++				mv "${x}" "${ED}"$(get_libdir)/ || die "could not move /${x#${ED}}"
 +			}
  		done
 -	else # keeping intendation to keep diff small
@@ -177,7 +176,7 @@
  	gen_usr_ldscript lib{,n}curses$(get_libname)
  	if use unicode ; then
  		gen_usr_ldscript libncursesw$(get_libname)
-@@ -216,6 +299,7 @@
+@@ -216,6 +298,7 @@
  		ln -sf libncurses$(get_libname) "${ED}"/usr/$(get_libdir)/libcurses$(get_libname) || die
  	fi
  	use static-libs || rm "${ED}"/usr/$(get_libdir)/*.a
@@ -185,7 +184,209 @@
  
  #	if ! use berkdb ; then
  		# We need the basic terminfo files in /etc, bug #37026
-@@ -241,6 +325,15 @@
+@@ -241,6 +324,15 @@
+ 	echo "CONFIG_PROTECT_MASK=\"/etc/terminfo\"" > "${T}"/50ncurses
+ 	doenvd "${T}"/50ncurses
+ 
++	if [[ ${CHOST} == *-cygwin* ]] ; then
++		# abi "10" is an artifact of cygwin history
++		# As far as external clients are concerned, this is ncurses API 6
++		mv "${ED}"/usr/bin/ncurses10-config "${ED}"/usr/bin/ncurses6-config
++		mv "${ED}"/usr/bin/ncursesw10-config "${ED}"/usr/bin/ncursesw6-config
++		sed -i -e "s/echo \"10\"/echo \"6\"/" "${ED}"/usr/bin/ncurses6-config
++		sed -i -e "s/echo \"10\"/echo \"6\"/" "${ED}"/usr/bin/ncursesw6-config
++	fi
++
+ 	use minimal && rm -r "${ED}"/usr/share/terminfo*
+ 	# Because ncurses5-config --terminfo returns the directory we keep it
+ 	keepdir /usr/share/terminfo #245374
+<---8<---
+---("sys-libs/ncurses/ncurses-5.9-r2.ebuild")--->8--->
+--- usr/portage/sys-libs/ncurses/ncurses-5.9-r2.ebuild [[PORTAGE]]
++++ overlay/sys-libs/ncurses/ncurses-5.9-r2.ebuild [[OVERLAY]]
+@@ -1,6 +1,6 @@
+ # Copyright 1999-2012 Gentoo Foundation
+ # Distributed under the terms of the GNU General Public License v2
+-# $Header: /var/cvsroot/gentoo-x86/sys-libs/ncurses/ncurses-5.9-r2.ebuild,v 1.12 2012/05/29 18:48:28 mr_bones_ Exp $
++# $Header: $
+ 
+ EAPI="1"
+ AUTOTOOLS_AUTO_DEPEND="no"
+@@ -32,8 +32,8 @@
+ 	# cannot depend on libtool, as this would create circular dependencies...
+ 	# And libtool-1.5.26 needs (a similar) patch for AIX (DESTDIR) as found in
+ 	# http://lists.gnu.org/archive/html/bug-libtool/2008-03/msg00124.html
+-	# Use libtool on hpux too to get some soname.
+-	[[ ${CHOST} == *'-aix'* || ${CHOST} == *'-hpux'* ]]
++	# Use libtool on hpux too to get some soname, and cygwin to avoid BROKEN_LINKER
++	[[ ${CHOST} == *'-aix'* || ${CHOST} == *'-hpux'* || ${CHOST} == *'-cygwin'* ]]
+ }
+ 
+ src_unpack() {
+@@ -51,6 +51,13 @@
+ 	epatch "${FILESDIR}"/${PN}-5.5-aix-shared.patch
+ 	epatch "${FILESDIR}"/${PN}-5.6-interix.patch
+ 
++	epatch "${FILESDIR}"/${PN}-5.9-cygwin-pthreads-suffix.patch
++	if [[ ${CHOST} == *-cygwin* ]] ; then
++		epatch "${FILESDIR}"/${PN}-5.9-cygwin-version-info.patch
++		# perhaps because it sets pwd to the location of the new ncurses dll,
++		# this subshell created by progs/Makefile causes rebase errors
++		epatch "${FILESDIR}"/${PN}-5.9-cygwin-subshell-avoidance.patch
++	fi
+ 	# /bin/sh is not always good enough
+ 	find . -name "*.sh" | xargs sed -i -e '1c\#!/usr/bin/env sh'
+ 
+@@ -105,6 +112,13 @@
+ 	cd "${WORKDIR}"/$1
+ 	shift
+ 
++	local going_wide=no
++	for arg in "$@" ; do
++		if [[ $arg == --enable-widec ]] ; then
++			going_wide=yes
++		fi
++	done
++
+ 	# The chtype/mmask-t settings below are to retain ABI compat
+ 	# with ncurses-5.4 so dont change em !
+ 	local conf_abi="
+@@ -119,6 +133,8 @@
+ 	local myconf=""
+ 	if need-libtool; then
+ 		myconf="${myconf} --with-libtool"
++		[[ ${CHOST} == *-cygwin* ]] && \
++			myconf="${myconf} --with-shared --with-normal"
+ 	elif [[ ${CHOST} == *-mint* ]]; then
+ 		:
+ 	else
+@@ -127,6 +143,33 @@
+ 
+ 	if [[ ${CHOST} == *-interix* ]]; then
+ 		myconf="--without-leaks"
++	elif [[ ${CHOST} == *-cygwin* ]] ; then
++		myconf="${myconf} --without-leaks"
++		# override most of the conf_abi defaults set above
++		conf_abi="--with-mmask-t=long --without-pthread --with-abi-version=10"
++		if [[ ${going_wide} == yes ]] ; then
++			conf_abi="${conf_abi} --enable-ext-colors"
++		else
++			conf_abi="${conf_abi} --disable-ext-colors "
++		fi
++		myconf="${myconf} --disable-relink"
++		myconf="${myconf} --disable-rpath"
++		myconf="${myconf} --with-ticlib"
++		myconf="${myconf} --without-termlib"
++		myconf="${myconf} --enable-ext-mouse"
++		myconf="${myconf} --enable-sp-funcs"
++		myconf="${myconf} --with-wrap-prefix=ncwrap_"
++		myconf="${myconf} --enable-sigwinch"
++		myconf="${myconf} --enable-tcap-names"
++		myconf="${myconf} --disable-mixed-case"
++		myconf="${myconf} --with-pkg-config"
++		myconf="${myconf} --enable-pc-files"
++		myconf="${myconf} --enable-reentrant"
++		# weaks are a disaster in cygwin, so why play with fire?  plus configure test barfs
++		myconf="${myconf} --disable-weak-symbols"
++		export cf_cv_weak_symbols=no
++	else
++		myconf="${myconf} $(use_enable debug leaks)"
+ 	fi
+ 
+ 	# We need the basic terminfo files in /etc, bug #37026.  We will
+@@ -155,7 +198,6 @@
+ 		--enable-pc-files \
+ 		$(use_enable !ada warnings) \
+ 		$(use_with debug assertions) \
+-		$(use_enable debug leaks) \
+ 		$(use_with debug expanded) \
+ 		$(use_with !debug macros) \
+ 		$(use_with trace) \
+@@ -170,6 +212,16 @@
+ 	need-libtool ||
+ 	sed -i -e '/^libdir/s:/usr/lib\(64\|\)$:/lib\1:' ncurses/Makefile || die "nlibdir"
+ 
++	if [[ ${CHOST} == *-cygwin* && ${going_wide} == yes ]] ; then
++		# There is a bug here -- there is code in configure which looks like its
++		# supposed to do this automatically but.. it doesn't.  If that bug ever
++		# got fixed, the following code would be harmless anyhow.
++		find . -name 'Makefile' | while read f ; do
++			sed -e 's/-D_XOPEN_SOURCE=500/& -D_XOPEN_SOURCE_EXTENDED=1/' -i "${f}" && \
++				einfo "Hacking up ${f} to use -D_XOPEN_SOURCE_EXTENDED=1"
++		done
++	fi
++
+ 	# Don't mess with _XOPEN_SOURCE for C++ on (Open)Solaris.  The compiler
+ 	# defines a value for it, and depending on version, a different definition
+ 	# is used.  Defining this variable on these systems is dangerous any time,
+@@ -185,6 +237,15 @@
+ 	# in parallel.  This is not really a perf hit since the source
+ 	# generation is quite small.
+ 	emake -j1 sources || die
++	if [[ ${CHOST} == *-cygwin* ]] ; then
++		# the cygport includes a hack to build libncurses before
++		# libtic, without which we get rare parallel build failures.
++		cd ncurses
++		local w=
++		[[ $going_wide == yes ]] && w=w
++		emake -j1 ../lib/libncurses${w}.la || die
++		cd ..
++	fi
+ 	# For some reason, sources depends on pc-files which depends on
+ 	# compiled libraries which depends on sources which ...
+ 	# Manually delete the pc-files file so the install step will
+@@ -208,17 +269,38 @@
+ 
+ 	if need-libtool; then
+ 		# Move dynamic ncurses libraries into /lib
+-		dodir /$(get_libdir)
+ 		local f
+-		for f in "${ED}"usr/$(get_libdir)/lib{,n}curses{,w}$(get_libname)*; do
++		local libpfx=lib
++		local shlibdir=$(get_libdir)
++		local suffix=
++		[[ ${CHOST} == *-cygwin* ]] && { libpfx=cyg; shlibdir=bin; suffix=-10; dodir /$(get_libdir); }
++		dodir /${shlibdir}
++		for f in "${ED}"usr/${shlibdir}/${libpfx}{,n}curses{,w}${suffix}$(get_libname)*; do
+ 			[[ -f ${f} ]] || continue
+-			mv "${f}" "${ED}"$(get_libdir)/ || die "could not move ${f#${ED}}"
++			einfo "moving \"/${f#${ED}}\" to \"/${shlibdir}/\"."
++			mv "${f}" "${ED}"${shlibdir}/ || die "could not move /${f#${ED}}"
++			[[ ${CHOST} == *-cygwin* ]] && {
++				local x="$( dirname ${f} )"
++				x="${x%${shlibdir}}$(get_libdir)"
++				x="${x}/lib$( foo=$(basename ${f}); foo="${foo%${suffix}.dll}" ; echo ${foo#cyg} ).dll.a"
++				einfo "moving \"/${x#${ED}}\" to \"/$(get_libdir)/\"."
++				mv "${x}" "${ED}"$(get_libdir)/ || die "could not move /${x#${ED}}"
++			}
+ 		done
+-	else # keeping intendation to keep diff small
++	elif ! need-libtool ; then # keeping intendation to keep diff small
+ 	# Move static and extraneous ncurses static libraries out of /lib
+ 	cd "${ED}"/$(get_libdir)
+ 	mv *.a "${ED}"/usr/$(get_libdir)/
+ 	fi
++	if [[ ${CHOST} == *-cygwin* ]] ; then
++		dodir /$(get_libdir)
++		cd "${ED}"$(get_libdir)
++		ln -s libncurses.dll.a libcurses.dll.a
++		gen_usr_ldscript lib{,n}curses.dll.a
++		use unicode && gen_usr_ldscript libncursesw.dll.a
++		cd "${ED}"usr/$(get_libdir)
++		ln -s libncurses.a libcurses.a
++	else
+ 	gen_usr_ldscript lib{,n}curses$(get_libname)
+ 	if use unicode ; then
+ 		gen_usr_ldscript libncursesw$(get_libname)
+@@ -227,6 +309,7 @@
+ 		ln -sf libncurses$(get_libname) "${ED}"/usr/$(get_libdir)/libcurses$(get_libname) || die
+ 	fi
+ 	use static-libs || rm "${ED}"/usr/$(get_libdir)/*.a
++	fi
+ 
+ #	if ! use berkdb ; then
+ 		# We need the basic terminfo files in /etc, bug #37026
+@@ -252,6 +335,15 @@
  	echo "CONFIG_PROTECT_MASK=\"/etc/terminfo\"" > "${T}"/50ncurses
  	doenvd "${T}"/50ncurses
  
@@ -210,6 +411,5 @@ overlay/sys-libs/ncurses/files/ncurses-5.9-cygwin-subshell-avoidance.patch: unif
 overlay/sys-libs/ncurses/files/ncurses-5.9-cygwin-version-info.patch: unified diff output, ASCII text
 
 *** The following files appear only in portage ***
-usr/portage/sys-libs/ncurses/ncurses-5.7-r6.ebuild: ASCII English text
 usr/portage/sys-libs/ncurses/ncurses-5.7-r7.ebuild: ASCII English text
 
