sys-apps/portage: return cygdll_protect to sanity
This fixes the most blatant problems that got introduced with the new
more complicated cygdll_protect semantics:

  o When unmerging a protected file that isn't present on the filesystem,
    do the right thing with the corresponding _cygdll_protect_foo files
    and in the database -- before we were forgetting to check if these
    were owned by packages that were just installed which was causing
    a horrible mess.
  o When merging a protected file that's already installed and out-of-
    limbo, don't forget to update the mtime, or at least to read it
    from the fs; otherwise, the file is orphaned!
  o stop trying to detect already-merged cygdll protections during
    the merge phase -- this was just too confusing and was causing
    wierd interactions
  o also touches up various in-source comments and error messages

diff --git a/portage_diffs/latest/sys-libs_ncurses b/portage_diffs/latest/sys-libs_ncurses
--- a/portage_diffs/latest/sys-libs_ncurses
+++ b/portage_diffs/latest/sys-libs_ncurses
@@ -101,7 +101,7 @@
  		$(use_with debug expanded) \
  		$(use_with !debug macros) \
  		$(use_with trace) \
-@@ -168,6 +210,16 @@
+@@ -168,12 +210,31 @@
  	need-libtool ||
  	sed -i -e '/^libdir/s:/usr/lib\(64\|\)$:/lib\1:' ncurses/Makefile || die "nlibdir"
  
@@ -118,7 +118,22 @@
  	# A little hack to fix parallel builds ... they break when
  	# generating sources so if we generate the sources first (in
  	# non-parallel), we can then build the rest of the package
-@@ -197,17 +249,39 @@
+ 	# in parallel.  This is not really a perf hit since the source
+ 	# generation is quite small.
+ 	emake -j1 sources || die
++	if [[ ${CHOST} == *-cygwin* ]] ; then
++		# the cygport includes a hack to build libncurses before
++		# libtic, without which we get rare parallel build failures.
++		cd ncurses
++		local w=
++		[[ $going_wide == yes ]] && w=w
++		emake -j1 ../lib/libncurses${w}.la || die
++		cd ..
++	fi
+ 	# For some reason, sources depends on pc-files which depends on
+ 	# compiled libraries which depends on sources which ...
+ 	# Manually delete the pc-files file so the install step will
+@@ -197,17 +258,39 @@
  
  	if need-libtool; then
  		# Move dynamic ncurses libraries into /lib
@@ -162,7 +177,7 @@
  	gen_usr_ldscript lib{,n}curses$(get_libname)
  	if use unicode ; then
  		gen_usr_ldscript libncursesw$(get_libname)
-@@ -216,6 +290,7 @@
+@@ -216,6 +299,7 @@
  		ln -sf libncurses$(get_libname) "${ED}"/usr/$(get_libdir)/libcurses$(get_libname) || die
  	fi
  	use static-libs || rm "${ED}"/usr/$(get_libdir)/*.a
@@ -170,7 +185,7 @@
  
  #	if ! use berkdb ; then
  		# We need the basic terminfo files in /etc, bug #37026
-@@ -241,6 +316,15 @@
+@@ -241,6 +325,15 @@
  	echo "CONFIG_PROTECT_MASK=\"/etc/terminfo\"" > "${T}"/50ncurses
  	doenvd "${T}"/50ncurses
  
