sys-libs/zlib: many updates
o Synchronize with upstream ebuilds
o implement new mask/unmask scheme to prevent non-overlay ebuilds
  from biting users in the ass in the future
o mask minigzip use-flag for ebuilds which don't support it
o version bump to sys-libs/zlib-1.2.7
o resync with cygport patches, including pulling new minigzip
  stuff from upstream cygport.
o synchronize metadata, Changelog

This adds minigzip use-flag support for cygwin zlib and masks it
for the old ebuilds which don't have it.  It is also the first
commit to implement the new scheme of future-proofing ebuilds which
won't work without overlay magic, by masking the package and
then unmasking the particular versions in the overlay.  Note that
this trick will only work due to prefix's ability to cascade
package.unmask updates through profiles.

Signed-off-by: Gregory M. Turner <gmturner007@ameritech.net>

diff --git a/portage_diffs/latest/sys-libs_zlib b/portage_diffs/latest/sys-libs_zlib
--- a/portage_diffs/latest/sys-libs_zlib
+++ b/portage_diffs/latest/sys-libs_zlib
@@ -2,41 +2,31 @@
 ---("sys-libs/zlib/ChangeLog")--->8--->
 --- usr/portage/sys-libs/zlib/ChangeLog [[PORTAGE]]
 +++ overlay/sys-libs/zlib/ChangeLog [[OVERLAY]]
-@@ -2,6 +2,9 @@
- # Copyright 1999-2011 Gentoo Foundation; Distributed under the GPL v2
- # $Header: /var/cvsroot/gentoo-x86/sys-libs/zlib/ChangeLog,v 1.97 2011/09/23 17:52:32 jlec Exp $
- 
-+  08 Mar 2012; Greg Turner <gmt@malth.us> zlib-1.2.5.1-r2.ebuild:
-+  apply cygport patches on cygwin.
+@@ -1,6 +1,9 @@
+ # ChangeLog for sys-libs/zlib
+ # Copyright 1999-2012 Gentoo Foundation; Distributed under the GPL v2
+-# $Header: /var/cvsroot/gentoo-x86/sys-libs/zlib/ChangeLog,v 1.108 2012/05/26 10:11:59 maekke Exp $
++# $Header: $
 +
-   14 Dec 2011; Fabian Groffen <grobian@gentoo.org> zlib-1.2.5.1-r2.ebuild:
-   Make sure we restore the working directory after minizip patching not to break
-   further patching, bug #394629
-<---8<---
----("sys-libs/zlib/metadata.xml")--->8--->
---- usr/portage/sys-libs/zlib/metadata.xml [[PORTAGE]]
-+++ overlay/sys-libs/zlib/metadata.xml [[OVERLAY]]
-@@ -2,7 +2,4 @@
- <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
- <pkgmetadata>
- 	<herd>base-system</herd>
--	<use>
--		<flag name="minizip">include the minizip library for quick and dirty zip extraction</flag>
--	</use>
- </pkgmetadata>
++  11 Aug 2012; Greg Turner <gmturner007@ameritech.net> zlib-1.2.7.ebuild:
++  Version bump for cygwin patches
+ 
+   05 Jun 2012; Fabian Groffen <grobian@gentoo.org> zlib-1.2.7.ebuild:
+   Add missing colon, thanks Richard Freeman in bug #419499
+@@ -42,6 +45,9 @@
+   01 May 2012; Jeroen Roovers <jer@gentoo.org> zlib-1.2.5.1-r2.ebuild:
+   Stable for HPPA (bug #384483).
+ 
++  08 Mar 2012; Greg Turner <gmturner007@ameritech.net> zlib-1.2.5.1-r2.ebuild:
++  apply cygport patches on cygwin
++
+   26 Apr 2012; Alexis Ballier <aballier@gentoo.org> zlib-1.2.6.ebuild:
+   keyword ~amd64-fbsd
+ 
 <---8<---
 ---("sys-libs/zlib/zlib-1.2.5-r2.ebuild")--->8--->
 --- usr/portage/sys-libs/zlib/zlib-1.2.5-r2.ebuild [[PORTAGE]]
 +++ overlay/sys-libs/zlib/zlib-1.2.5-r2.ebuild [[OVERLAY]]
-@@ -2,7 +2,7 @@
- # Distributed under the terms of the GNU General Public License v2
- # $Header: /var/cvsroot/gentoo-x86/sys-libs/zlib/zlib-1.2.5-r2.ebuild,v 1.12 2011/05/01 09:52:06 xarthisius Exp $
- 
--inherit eutils toolchain-funcs
-+inherit eutils toolchain-funcs autotools
- 
- DESCRIPTION="Standard (de)compression library"
- HOMEPAGE="http://www.zlib.net/"
 @@ -42,6 +42,8 @@
  #	epatch "${FILESDIR}"/${PN}-1.2.3-shlib-aix.patch
  	# patch breaks shared libs installation
@@ -67,17 +57,15 @@
 ---("sys-libs/zlib/zlib-1.2.5.1-r2.ebuild")--->8--->
 --- usr/portage/sys-libs/zlib/zlib-1.2.5.1-r2.ebuild [[PORTAGE]]
 +++ overlay/sys-libs/zlib/zlib-1.2.5.1-r2.ebuild [[OVERLAY]]
-@@ -1,8 +1,7 @@
- # Copyright 1999-2011 Gentoo Foundation
+@@ -1,6 +1,6 @@
+ # Copyright 1999-2012 Gentoo Foundation
  # Distributed under the terms of the GNU General Public License v2
--# $Header: /var/cvsroot/gentoo-x86/sys-libs/zlib/zlib-1.2.5.1-r2.ebuild,v 1.3 2011/09/23 17:52:32 jlec Exp $
+-# $Header: /var/cvsroot/gentoo-x86/sys-libs/zlib/zlib-1.2.5.1-r2.ebuild,v 1.10 2012/05/26 10:11:59 maekke Exp $
 +# $Header: $
  
--AUTOTOOLS_AUTO_DEPEND="no"
+ AUTOTOOLS_AUTO_DEPEND="no"
  inherit autotools eutils toolchain-funcs
- 
- DESCRIPTION="Standard (de)compression library"
-@@ -38,6 +37,9 @@
+@@ -38,6 +38,9 @@
  
  	epatch "${FILESDIR}"/${P}-aix-soname.patch #213277
  
@@ -87,7 +75,7 @@
  	# also set soname and stuff on Solaris (with CHOST compensation fix as below)
  	sed -i -e 's:Linux\* | linux\*:Linux\* | linux\* | SunOS\* | solaris\*:' configure || die
  	# and compensate for our ebuild env having CHOST set
-@@ -71,6 +73,16 @@
+@@ -71,6 +74,16 @@
  		echoit ./configure --static --prefix="${EPREFIX}"/usr --libdir="${EPREFIX}"/usr/$(get_libdir) || die
  		emake || die
  		;;
@@ -104,18 +92,63 @@
  	*)	# not an autoconf script, so can't use econf
  		echoit ./configure --shared --prefix="${EPREFIX}"/usr --libdir="${EPREFIX}"/usr/$(get_libdir) || die
  		emake || die
-@@ -100,9 +112,8 @@
- 		insinto /usr/share/pkgconfig
- 		doins zlib.pc || die
+@@ -123,5 +136,12 @@
+ 		dodoc *.txt
+ 	fi
+ 
+-	use static-libs || rm -f "${ED}"/usr/$(get_libdir)/*.{a,la}
++	use static-libs || {
++		if [[ ${CHOST} == *-cygwin* ]] ; then
++			rm -v -f "${ED}"/usr/$(get_libdir)/$( \
++				cd "${ED}"/usr/$(get_libdir) ; ls *.{a,la} 2>/dev/null | grep -v '\.dll\.a$' )
++		else
++			rm -f "${ED}"/usr/$(get_libdir)/*.{a,la}
++		fi
++	}
+ }
+<---8<---
+---("sys-libs/zlib/zlib-1.2.7.ebuild")--->8--->
+--- usr/portage/sys-libs/zlib/zlib-1.2.7.ebuild [[PORTAGE]]
++++ overlay/sys-libs/zlib/zlib-1.2.7.ebuild [[OVERLAY]]
+@@ -1,6 +1,6 @@
+ # Copyright 1999-2012 Gentoo Foundation
+ # Distributed under the terms of the GNU General Public License v2
+-# $Header: /var/cvsroot/gentoo-x86/sys-libs/zlib/zlib-1.2.7.ebuild,v 1.2 2012/05/03 19:08:41 vapier Exp $
++# $Header: $
+ 
+ AUTOTOOLS_AUTO_DEPEND="no"
+ inherit autotools toolchain-funcs eutils
+@@ -23,6 +23,12 @@
+ 	unpack ${A}
+ 	cd "${S}"
+ 
++	if [[ ${CHOST} == *-cygwin* ]] ; then
++		epatch "${FILESDIR}"/${PN}-1.2.7-cygport-ish.patch
++		epatch "${FILESDIR}"/${PN}-1.2.7-cygwin-fix-parallel-make.patch
++		epatch "${FILESDIR}"/${PN}-1.2.7-cygwin-minizip-anti-maintainer-mode.patch
++	fi
++
+ 	if use minizip ; then
+ 		pushd contrib/minizip > /dev/null || die
+ 		eautoreconf
+@@ -56,6 +62,16 @@
+ 		echoit ./configure --static --prefix="${EPREFIX}"/usr --libdir="${EPREFIX}"/usr/$(get_libdir) || die
+ 		emake || die
  		;;
--
- 	*)
--		emake install DESTDIR="${D}" LDCONFIG=: || die
-+		emake install DESTDIR="${D}" LDCONFIG=: || die "make install failed"
- 		gen_usr_ldscript -a z
- 		sed_macros "${ED}"/usr/include/*.h
- 		;;
-@@ -123,5 +134,12 @@
++	*-cygwin*)
++		# AC_HAVE_MMAP fails despite a working mmap, so we force this to yes
++		# (see http://www.cygwin.com/ml/cygwin/2004-09/msg00741.html
++		# and following thread for details)
++		export ac_cv_func_mmap_fixed_mapped=yes
++		echoit ./configure --shared --prefix="${EPREFIX%/}"/usr --eprefix="${EPREFIX%/}"/usr \
++			--libdir="${EPREFIX%/}"/usr/$(get_libdir) --sharedlibdir="${EPREFIX}"/usr/$(get_libdir) \
++			--includedir="${EPREFIX%/}"/usr/include || die
++		emake -j1 || die
++		;;
+ 	*)	# not an autoconf script, so can't use econf
+ 		echoit ./configure --shared --prefix="${EPREFIX}"/usr --libdir="${EPREFIX}"/usr/$(get_libdir) || die
+ 		emake || die
+@@ -108,5 +124,12 @@
  		dodoc *.txt
  	fi
  
@@ -135,6 +168,9 @@
 *** The following files appear only in the overlay ***
 overlay/sys-libs/zlib/files/zlib-1.2.5-cygport.patch: unified diff output, ASCII text
 overlay/sys-libs/zlib/files/zlib-1.2.5.1-cygport-ish.patch: unified diff output, ASCII text
+overlay/sys-libs/zlib/files/zlib-1.2.7-cygport-ish.patch: unified diff output, ASCII text
+overlay/sys-libs/zlib/files/zlib-1.2.7-cygwin-fix-parallel-make.patch: unified diff output, ASCII text
+overlay/sys-libs/zlib/files/zlib-1.2.7-cygwin-minizip-anti-maintainer-mode.patch: unified diff output, ASCII text
 
 *** The following files appear only in portage ***
 usr/portage/sys-libs/zlib/zlib-1.2.3-r01.1.ebuild: ASCII English text
