update portage_diffs/latest

diff --git a/portage_diffs/latest/sys-apps_coreutils b/portage_diffs/latest/sys-apps_coreutils
--- a/portage_diffs/latest/sys-apps_coreutils
+++ b/portage_diffs/latest/sys-apps_coreutils
@@ -1,8 +1,56 @@
 ===== mutual sub-directory: "sys-apps/coreutils" =====
+--("sys-apps/coreutils/ChangeLog")-->8-->
+--- usr/portage/sys-apps/coreutils/ChangeLog	2012-02-14 13:31:30.000000000 -0800
++++ overlay/sys-apps/coreutils/ChangeLog	2011-10-22 09:31:37.000000000 -0700
+@@ -1,36 +1,6 @@
+ # ChangeLog for sys-apps/coreutils
+-# Copyright 1999-2012 Gentoo Foundation; Distributed under the GPL v2
+-# $Header: /var/cvsroot/gentoo-x86/sys-apps/coreutils/ChangeLog,v 1.333 2012/02/02 15:23:23 ssuominen Exp $
+-
+-  14 Feb 2012; Fabian Groffen <grobian@gentoo.org> coreutils-8.15.ebuild:
+-  Forcibly use bash, since e.g. dash seems to hang configure
+-
+-  02 Feb 2012; Samuli Suominen <ssuominen@gentoo.org> coreutils-8.14.ebuild:
+-  ppc64 stable wrt #397929
+-
+-  01 Feb 2012; Brent Baude <ranger@gentoo.org> coreutils-8.14.ebuild:
+-  Marking coreutils-8.14 ppc for bug 397929
+-
+-  21 Jan 2012; Pawel Hajdan jr <phajdan.jr@gentoo.org> coreutils-8.14.ebuild:
+-  x86 stable wrt bug #397929
+-
+-  18 Jan 2012; Markus Meier <maekke@gentoo.org> coreutils-8.14.ebuild:
+-  arm stable, bug #397929
+-
+-  17 Jan 2012; Jeroen Roovers <jer@gentoo.org> coreutils-8.14.ebuild:
+-  Stable for HPPA (bug #397929).
+-
+-  07 Jan 2012; Agostino Sarubbo <ago@gentoo.org> coreutils-8.14.ebuild:
+-  Stable for AMD64, wrt bug #397929
+-
+-*coreutils-8.15 (06 Jan 2012)
+-
+-  06 Jan 2012; Mike Frysinger <vapier@gentoo.org> +coreutils-8.15.ebuild:
+-  Version bump.
+-
+-  10 Dec 2011; Fabian Groffen <grobian@gentoo.org> coreutils-8.14.ebuild:
+-  Fix compilation on FreeBSD, override the pthread check which incorrectly
+-  concludes no libs are necessary
++# Copyright 1999-2011 Gentoo Foundation; Distributed under the GPL v2
++# $Header: /var/cvsroot/gentoo-x86/sys-apps/coreutils/ChangeLog,v 1.326 2011/10/18 22:47:25 vapier Exp $
+ 
+   18 Oct 2011; Mike Frysinger <vapier@gentoo.org> coreutils-8.14.ebuild:
+   Extend man page hack to missing perl #387091 by nzqr.
+<--8<--
 --("sys-apps/coreutils/coreutils-8.14.ebuild")-->8-->
---- usr/portage/sys-apps/coreutils/coreutils-8.14.ebuild	2011-10-22 09:31:37.000000000 -0700
-+++ overlay/sys-apps/coreutils/coreutils-8.14.ebuild	2012-02-24 13:19:00.429238000 -0800
-@@ -4,7 +4,7 @@
+--- usr/portage/sys-apps/coreutils/coreutils-8.14.ebuild	2012-02-14 12:01:29.000000000 -0800
++++ overlay/sys-apps/coreutils/coreutils-8.14.ebuild	2012-03-06 14:10:18.351031100 -0800
+@@ -1,10 +1,10 @@
+-# Copyright 1999-2012 Gentoo Foundation
++# Copyright 1999-2011 Gentoo Foundation
+ # Distributed under the terms of the GNU General Public License v2
+-# $Header: /var/cvsroot/gentoo-x86/sys-apps/coreutils/coreutils-8.14.ebuild,v 1.8 2012/02/02 15:23:23 ssuominen Exp $
++# $Header: /var/cvsroot/gentoo-x86/sys-apps/coreutils/coreutils-8.14.ebuild,v 1.2 2011/10/18 22:47:25 vapier Exp $
  
  EAPI="3"
  
@@ -16,7 +64,7 @@
  		epatch "${FILESDIR}"/${PN}-8.5-interix-double.patch
  
 +	[[ ${CHOST} == *-cygwin* ]] && {
-+		epatch "${FILESDIR}"/${PN}-8.14-1-cygport-src.patch
++		epatch "${FILESDIR}"/${PN}-${PV}-cygport-src.patch
 +		epatch "${FILESDIR}"/${PN}-8.14-cygwin-tests.patch
 +		epatch "${FILESDIR}"/${PN}-8.14-scrub-cygwin-unc.patch
 +		eautoreconf
@@ -27,7 +75,75 @@
  	# Since we've patched many .c files, the make process will try to
  	# re-build the manpages by running `./bin --help`.  When doing a
  	# cross-compile, we can't do that since 'bin' isn't a native bin.
-@@ -168,14 +177,23 @@
+@@ -89,10 +98,6 @@
+ 
+ 	tc-is-cross-compiler && [[ ${CHOST} == *linux* ]] && export fu_cv_sys_stat_statfs2_bsize=yes #311569
+ 
+-	# m4/pthread.m4 on FreeBSD thinks pthread_join doesn't need any libaries
+-	# sort.c:(.text+0x4f25): undefined reference to `pthread_create'
+-	[[ ${CHOST} == *-freebsd* ]] && export gl_cv_search_pthread_join=-pthread
+-
+ 	use static && append-ldflags -static && sed -i '/elf_sys=yes/s:yes:no:' configure #321821
+ 	use selinux || export ac_cv_{header_selinux_{context,flash,selinux}_h,search_setfilecon}=no #301782
+ 	# kill/uptime - procps
+@@ -172,14 +177,23 @@
+ 
+ 		[[ ${CHOST} == *-mint* ]] && fhs="${fhs} hostname"
+ 
++		[[ ${CHOST} == *-cygwin* ]] && \
++			fhs="$( for x in $fhs; do echo ${x}.exe ; done )"
++
+ 		mv ${fhs} ../../bin/ || die "could not move fhs bins"
+ 		# move critical binaries into /bin (common scripts)
+ 		local com="basename chroot cut dir dirname du env expr head mkfifo
+ 		           mktemp readlink seq sleep sort tail touch tr tty vdir wc yes"
++		[[ ${CHOST} == *-cygwin* ]] &&
++			com="$( for x in $com ; do echo ${x}.exe ; done )"
+ 		mv ${com} ../../bin/ || die "could not move common bins"
+ 		# create a symlink for uname in /usr/bin/ since autotools require it
+-		local x
+-		for x in ${com} uname ; do
++		local x unamename
++		case ${CHOST} in
++			*-cygwin*) unamename=uname.exe ;;
++			*) unamename=uname ;;
++		esac
++		for x in ${com} ${unamename}; do
+ 			dosym /bin/${x} /usr/bin/${x} || die
+ 		done
+ 	else
+<--8<--
+--("sys-apps/coreutils/coreutils-8.15.ebuild")-->8-->
+--- usr/portage/sys-apps/coreutils/coreutils-8.15.ebuild	2012-02-14 13:31:30.000000000 -0800
++++ overlay/sys-apps/coreutils/coreutils-8.15.ebuild	2012-03-06 16:38:26.211031100 -0800
+@@ -4,7 +4,7 @@
+ 
+ EAPI="3"
+ 
+-inherit eutils flag-o-matic toolchain-funcs
++inherit eutils flag-o-matic toolchain-funcs autotools
+ 
+ PATCH_VER="1"
+ DESCRIPTION="Standard GNU file utilities (chmod, cp, dd, dir, ls...), text utilities (sort, tr, head, wc..), and shell utilities (whoami, who,...)"
+@@ -66,6 +66,17 @@
+ 	[[ ${CHOST} == *-interix* ]] &&
+ 		epatch "${FILESDIR}"/${PN}-8.5-interix-double.patch
+ 
++	[[ ${CHOST} == *-cygwin* ]] && {
++		# avoid maintainer mode
++		epatch "${FILESDIR}"/${PN}-8.15-am_maintainer_mode.patch
++		epatch "${FILESDIR}"/${PN}-${PV}-cygport-src.patch
++		epatch "${FILESDIR}"/${PN}-8.14-cygwin-tests.patch
++		epatch "${FILESDIR}"/${PN}-8.14-scrub-cygwin-unc.patch
++		eautoreconf
++	}
++
++	epatch "${FILESDIR}"/${PN}-8.14-cygwin-hostglob.patch
++
+ 	# Since we've patched many .c files, the make process will try to
+ 	# re-build the manpages by running `./bin --help`.  When doing a
+ 	# cross-compile, we can't do that since 'bin' isn't a native bin.
+@@ -176,14 +187,23 @@
  
  		[[ ${CHOST} == *-mint* ]] && fhs="${fhs} hostname"
  
@@ -57,12 +173,12 @@
 ===== mutual sub-directory: "sys-apps/coreutils/files" =====
 
 *** The following files appear only in the overlay ***
-overlay/sys-apps/coreutils/setup.log: ASCII text, with CRLF line terminators
-overlay/sys-apps/coreutils/setup.log.full: ASCII text, with CRLF line terminators
-overlay/sys-apps/coreutils/files/coreutils-8.14-1-cygport-src.patch: unified diff output, ASCII text
+overlay/sys-apps/coreutils/files/coreutils-8.14-cygport-src.patch: unified diff output, ASCII text
 overlay/sys-apps/coreutils/files/coreutils-8.14-cygwin-hostglob.patch: unified diff output, ASCII text
 overlay/sys-apps/coreutils/files/coreutils-8.14-cygwin-tests.patch: unified diff output, ASCII text
 overlay/sys-apps/coreutils/files/coreutils-8.14-scrub-cygwin-unc.patch: unified diff output, ASCII text
+overlay/sys-apps/coreutils/files/coreutils-8.15-am_maintainer_mode.patch: unified diff output, ASCII text
+overlay/sys-apps/coreutils/files/coreutils-8.15-cygport-src.patch: unified diff output, UTF-8 Unicode text
 
 *** The following files appear only in portage ***
 usr/portage/sys-apps/coreutils/coreutils-8.12.ebuild: ASCII English text
